#!/bin/bash
PATH=./node_modules/.bin:$PATH

###############################################################################
# ACTIONS

function main {
  echo "This is the main action"
  echo
  echo "Sequential actions:"

  one
  two testing
  echo "Actions one and two completed"

  echo
  echo "Concurrent actions:"

  one & two
  wait

  echo "Actions one and two completed concurrently"
  echo
}

function one {
  echo "> This is action one"
}

function two {
  if [ "$1" != "" ]; then
    echo "> This is action two (parameter \$1 = $1)"
  else
    echo "> This is action two (no parameter)"
  fi
}

###############################################################################
# DEFAULT => INFO

function default {
  echo "$0 <task> <args>"
  echo
  echo "Available tasks:"
  compgen -A function | cat -n
}


TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
